### ISSUE TITLE
COGS is not processing the Go Button Pressed

### ISSUE THREAD

**Issue by SecurityHat** [clockwork-dog/cra-template-cogs-client#15]
GOCS is not processing the Go Button Pressed:

![image](https://github.com/clockwork-dog/cra-template-cogs-client/assets/90387792/26356444-d85c-4cc8-bddd-640a500d9e1a)
![image](https://github.com/clockwork-dog/cra-template-cogs-client/assets/90387792/20218396-8623-4d36-9985-7ee298ffa22f)

```
cogs-plugin-manifest.js
toCogs: [
        {`
          name: "Go Button Pressed",`

App.tsx
<div
          className="button go"
          onClick={() => cogsConnection.sendEvent("Go Button Pressed")}
        >
          GO!
        </div>
```

**Comment by tomdixon** [comment]
Hey @SecurityHat, to react to that event in COGS, you'll need to add a behaviour and choose the "Device Event" option, and you should then see your event as an option when configuring the event:

<img width="326" alt="image" src="https://github.com/clockwork-dog/cra-template-cogs-client/assets/3168994/4ee31c2f-fc89-4785-ab4f-8e6af6a17498">
